#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#include "file.h"

void toUpperCase( char * );

int main( int argc, char **argv ) {
	initFile( );

	if ( argc != 4 ) {
		fprintf( stderr, "84link: incorrect number of arguments.\n" );
			printf(
			"84link: A tool to convert z80 binaries into .8xp files.\n"
			"Usage: 84link [/path/to/binary] [/path/to/8xp] [progName]\n"
			"progName must be 8 characters or less.\n"
			"Please type the .8xp extension.\n"
			"version 1.0: Created by bobxonar (2020).\n\n"
		);
		exit( EXIT_FAILURE );
	}

	printf(
		"\n84link: A tool to convert z80 binaries into .8xp files.\n"
		"Usage: 84link [/path/to/binary] [/path/to/8xp] [progName]\n"
		"progName must be 8 characters or less.\n"
		"Please type the .8xp extension.\n"
		"version 1.0: Created by bobxonar (2020).\n\n"
	);

	char com[43] = { 0 };
	strcpy( com, "Generated by 84link" );
	char fname[256] = { 0 };
	char pname[9] = { 0 };
	strncpy( pname, argv[3], 8 );
	toUpperCase( pname );
	
	
	FILE *xp8 = fopen( argv[2], "wb+" );
	FILE *bin = fopen( argv[1], "rb" );

	L84File.firstEleven( xp8 );
	L84File.writeComment( xp8, com );
	L84File.writeSubheader( xp8, bin, pname );
	uint16_t checksum = L84File.getChecksum( xp8 );
	L84File.writeChecksum( xp8, checksum );

	printf( "Success!\n" );
	return 0;
	
}

void toUpperCase( char *str ) {
	for ( size_t i = 0; i < strlen( str ); i++ )
		if ( str[i] > 0x60 && str[i] < 0x7B )
			str[i] -= 0x20;
}